### ISSUE TITLE
Scrolling does not work for goto and search commands

### ISSUE THREAD

**Issue by timjs** [71/dance#22]
[Remnant](https://github.com/71/dance/issues/15#issuecomment-555950974) of #15?

**Comment by 71** [comment]
Huh, I can't reproduce for some reason, both for goto, search, and move with the fix (bb84bfd3f1d6b6307770b385de465d6347048c43) removed

**Comment by 71** [comment]
If I get to reproduce though I have a good idea of what I should change to fix it.

**Comment by timjs** [comment]
Can you publish a new version? I’ll check if it still happens there.

**Comment by 71** [comment]
Done (it will be live in a few minutes).

**Comment by timjs** [comment]
Thanks!

I'm sorry but I still have problems. To reproduce:

0. Load a text file that is longer than fits on screen.
1. Hit `/` and search for something that is not on screen.

The editor will not scroll to the position of the cursor. It will show where the cursor is in the scroll bar, and after hitting `h/j/k/l` the editor will scroll to show the cursor. Same happens when hitting `n` after a search or when performing a goto using `g` and friends.

**Comment by 71** [comment]
Can you tell me your VS Code version?

I can reproduce on one of my computers, but not on my main development machine. Strange. But at least I know how to debug it. I'll work on it.

**Comment by sebsebmc** [comment]
I have the same problem. Im using VS Code 1.40.1 on Windows

**Comment by timjs** [comment]
This is my version info:

```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by 71** [comment]
I think another extension of mine actually took care of it... In any case my last commit should fix it.
